---
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.7.3
    hooks:
      # Run the linter.
      - id: ruff
        args: [
            --fix,
            "--select",
            "D",
            "--ignore",
            "D100,D101,D102,D103,D104,D105,D107,D404,D401", # Ignore missing docstrings.
          ]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        args:
          - --ignore-words-list=clos,htmp,ser,chck
          - --skip="*.json"
          - --quiet-level=2
        exclude_types: [csv, json]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: ["--quiet", "-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.1
    hooks:
      - id: mypy
        additional_dependencies:
          [types-requests, types-python-dateutil, types-pyyaml]
        args:
          - --pretty
          - --show-error-codes
          - --show-error-context
          - --ignore-missing-imports
          - --explicit-package-bases
